# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20180728_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwarehouse',
            name='customer_transport',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Received', 'Received')], default='Waiting', max_length=50),
        ),
    ]
