# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20180728_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='aw_executive',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='aw_manager',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='is_device_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='returned_from',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='transport_person_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
