# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20180730_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citywarehouse',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='aw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.AssemblyWarehouse'),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='cw_executive',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='cw_manager',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='returned_from',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='transport_person_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='cw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.CityWarehouse'),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='returned_from',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='sw_executive',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='sw_manager',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='transport_person_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
