# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_remove_subwarehouse_sw_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblywarehouse',
            name='end_transport',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assemblywarehouse',
            name='return_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assemblywarehouse',
            name='start_transport',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citywarehouse',
            name='end_transport',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citywarehouse',
            name='return_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='citywarehouse',
            name='start_transport',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subwarehouse',
            name='end_transport',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subwarehouse',
            name='return_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subwarehouse',
            name='start_transport',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
