# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20180731_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCityWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw_name', models.CharField(blank=True, max_length=500)),
                ('cw_manager', models.CharField(blank=True, max_length=500)),
                ('cw_executive', models.CharField(blank=True, max_length=500)),
                ('cw_manager_active', models.BooleanField(default=True)),
                ('cw_executive_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalSubWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_name', models.CharField(blank=True, max_length=500)),
                ('sw_manager', models.CharField(blank=True, max_length=500)),
                ('sw_executive', models.CharField(blank=True, max_length=500)),
                ('sw_manager_active', models.BooleanField(default=True)),
                ('sw_executive_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='end_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
