# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20180801_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assemblywarehouse',
            name='start_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='end_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citywarehouse',
            name='start_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='end_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='start_transport',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
